title: Metafacture Documentation
description: This is the central place for the documentation about Metafacture.
theme: just-the-docs

url: https://Phu2.github.io/metafacture-documentation

aux_links:
  Metafacture Documentation on Github: https://github.com/Phu2/metafacture-documentation

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/metafacture_small.png"
favicon_ico: "/assets/images/favicon.ico"
