title: Metafacture Documentation
description: This is the central place for the documentation about Metafacture.
theme: just-the-docs

url: https://Phu2.github.io/metafacture-documentation

aux_links:
  Template Repository: https://github.com/Phu2/metafacture-documentation
